version: '3.9'

services:
   
  java-appUniversidad:
    container_name: java-appUniversidad
    image: universidad:latest
    build: .
    ports:
      - "8082:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java-dbPosgres:5432/postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_USERNAME=postgres
    depends_on:
      - java-dbPosgres

  java-dbPosgres:
    container_name: java-dbPosgres
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: